title: Sota Kitamura (北村 想太)
url: "http://morimoto-lab.t.u-tokyo.ac.jp"
baseurl: "/kitamura"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: UA-145131085-1

footer: no
#footer_url: "https://github.com/ankitsultana"
#footer_text: "Page design by Ankit Sultana"
#footer_text: <a href="https://jekyllrb.com/" style="color: black">jekyll</a>  <a href="https://github.com/ankitsultana/researcher" style="color: black">researcher</a>  <a href="https://jpswalsh.github.io/academicons/" style="color: black">academicons</a>

sass:
    style: compressed
    sass_dir: _sass

nav:
# - name: "About"
#   link: "/researcher/"
# - name: "Resume"
#   link: "resume.pdf"
 - name: <i class="fas fa-home fa-lg" title="Group"></i>
   link: "http://morimoto-lab.t.u-tokyo.ac.jp"
 - name: <i class="ai ai-google-scholar-square ai-lg" title="Google Scholar"></i>
   link: "https://scholar.google.co.jp/citations?user=_HyaTKkAAAAJ"
 - name: <i class="ai ai-semantic-scholar ai-lg" title="Semantic Scholar"></i>
   link: "https://www.semanticscholar.org/author/Sota-Kitamura/13441915"
 - name: <i class="ai ai-clarivate-square ai-lg" title="Web of Science"></i>
   link: "https://www.webofscience.com/wos/author/rid/N-6794-2018"
 - name: <i class="ai ai-arxiv ai-lg" title="arXiv"></i>
   link: "https://arxiv.org/a/kitamura_s_1.html"
 - name: <i class="ai ai-orcid ai-lg" title="ORCID"></i>
   link: "https://orcid.org/0000-0003-3083-2353"
 - name: <i class="fas fa-play fa-fw" title="researchmap"></i>
   link: "https://researchmap.jp/sotak/"


nav2:
 - name: "Top"
   link: "/kitamura/"
 - name: "研究紹介"
   link: "/kitamura/research/"
# - name: "夏学講義ページ"
#   link: "/kitamura/cmpss67/"
